<a href="https://colab.research.google.com/github/Solayman-Emon/Python_Practise/blob/master/python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install numpy

In [0]:
import numpy as np

In [0]:
# convert list in numpy array
# numpy array is faster than list, numpy is very useful for faster multiplication

list = [1, 3, 4, 6]
arr = np.array(list)
arr


array([1, 3, 4, 6])

In [0]:
# nested list

list = [[1, 3, 2], [2, 1, -2]]
arr = np.array(list)            # like matrix
arr

list1 = [[1, 2], [2, 4, 6]]
arr1 = np.array(list1)        # when data imbalance happen, it treat as individual list
arr1

array([list([1, 2]), list([2, 4, 6])], dtype=object)

In [0]:
# arang(start, stop, step, dtype)   # step means the spacing between values 
arr = np.arange(0, 10, 2, float)  # first parameter is starting, second parameter is ending...
arr

array([0., 2., 4., 6., 8.])

In [0]:
# creating array with zeros

arr = np.zeros(4)  # 1D array
arr

arr1 = np.zeros((4, 3), dtype = int) # 2D matrix
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
# creating array with ones

arr = np.ones((4, 3, 2), dtype = int) # 3D matrix
arr

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [0]:
# array with custom array

arr = np.full((4, 3), 10)
arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [0]:
# identity matrix

arr = np.eye(5, dtype = int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [0]:
arr = np.linspace(0, 10, 100)  # 0 - 10, 100 distributions
arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [0]:
arr = np.logspace(0, 10, base = np.e)
arr

array([1.00000000e+00, 1.22639826e+00, 1.50405270e+00, 1.84456762e+00,
       2.26217453e+00, 2.77432691e+00, 3.40242971e+00, 4.17273388e+00,
       5.11743359e+00, 6.27601167e+00, 7.69688981e+00, 9.43945230e+00,
       1.15765279e+01, 1.41974337e+01, 1.74117081e+01, 2.13536885e+01,
       2.61881265e+01, 3.21170729e+01, 3.93883224e+01, 4.83057703e+01,
       5.92421128e+01, 7.26544242e+01, 8.91032597e+01, 1.09276083e+02,
       1.34015998e+02, 1.64356988e+02, 2.01567124e+02, 2.47201571e+02,
       3.03167578e+02, 3.71804191e+02, 4.55980014e+02, 5.59213097e+02,
       6.85817972e+02, 8.41085969e+02, 1.03150637e+03, 1.26503762e+03,
       1.55143995e+03, 1.90268325e+03, 2.33344744e+03, 2.86173589e+03,
       3.50962792e+03, 4.30420159e+03, 5.27866536e+03, 6.47374603e+03,
       7.93939089e+03, 9.73685520e+03, 1.19412623e+04, 1.46447434e+04,
       1.79602878e+04, 2.20264658e+04])

In [0]:
# diagonal matrix 

arr = np.diag([2, 4, 6])
arr

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [0]:
# random numbers

arr = np.random.rand(3) # 1D array of random numbers
arr1 = np.random.rand(3, 4, 3) # 2D array of random numbers
arr1

array([[[0.32424569, 0.92147588, 0.61871092],
        [0.91968302, 0.26081723, 0.53401318],
        [0.83733892, 0.86995581, 0.92924746],
        [0.44260373, 0.78008223, 0.98611836]],

       [[0.82356335, 0.79563134, 0.27507484],
        [0.25751425, 0.19749681, 0.23238622],
        [0.55351859, 0.36651408, 0.26618464],
        [0.54864582, 0.32790828, 0.2949856 ]],

       [[0.19411705, 0.20892693, 0.51824925],
        [0.03114849, 0.57174481, 0.9054098 ],
        [0.83977999, 0.46700877, 0.12543556],
        [0.79787963, 0.08509522, 0.45512166]]])

In [0]:
# standard normal distributed random values

arr = np.random.randn(4)
arr
arr1 = np.random.randn(3, 4)
arr1

array([[ 0.63377952, -0.64622954,  0.31479533, -0.33197122],
       [ 0.3006031 , -0.22233072,  0.56612701, -1.67806269],
       [-0.79529002,  0.96546973, -1.23349397,  2.22992399]])

In [0]:
arr = np.random.randint(0, 10, 11, dtype = int)  # first parameter is start, second is end, third parameter is number of random numbers in that range
arr                                              # start value may include in result, but end value does not include in the result
                                                 # dtype = float doesn't support

array([7, 3, 5, 9, 0, 7, 7, 1, 6, 5, 5])