<a href="https://colab.research.google.com/github/Solayman-Emon/Python_Practise/blob/master/python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install pandas

In [0]:
from google.colab import files
uploaded = files.upload()

Saving demo.csv to demo.csv
Saving demo.xlsx to demo.xlsx
Saving demo1.csv to demo1.csv


In [0]:
import numpy as np
import pandas as pd

In [0]:
df = pd.read_csv("demo.csv")                     # df is the dataframe
df1 = pd.read_csv("demo1.csv", delimiter = "-")
df2 = pd.read_csv("demo1.csv")
print(df)
print(df1)
print(df2)
df

df.to_csv("demo2.csv", index = True)    # copy dataframe to a csv
df.to_csv("demo3.csv", index = False)

df3 = pd.read_csv("demo2.csv")
print(df3)
df4 = pd.read_csv("demo3.csv")
print(df4)


             ID                   Name Department
0  16.01.04.091  Solayman Hossain Emon        CSE
1  16.01.04.090           Shaon Mahbub        CSE
             ID                   Name Department
0  16.01.04.091  Solayman Hossain Emon        CSE
1  16.01.04.090           Shaon Mahbub        CSE
                       ID-Name-Department
0  16.01.04.091-Solayman Hossain Emon-CSE
1           16.01.04.090-Shaon Mahbub-CSE
   Unnamed: 0            ID                   Name Department
0           0  16.01.04.091  Solayman Hossain Emon        CSE
1           1  16.01.04.090           Shaon Mahbub        CSE
             ID                   Name Department
0  16.01.04.091  Solayman Hossain Emon        CSE
1  16.01.04.090           Shaon Mahbub        CSE


In [0]:
!pip install xlrd
!pip install openpyxl

In [0]:
df = pd.read_excel("demo.xlsx")
print(df)
df.to_excel("demo1.xlsx")
df1 = pd.read_excel("demo.xlsx")
df1


             ID                   Name Department
0  16.01.04.091  Solayman Hossain Emon        CSE
1  16.01.04.090           Shaon Mahbub        CSE


ID                   Name Department
0  16.01.04.091  Solayman Hossain Emon        CSE
1  16.01.04.090           Shaon Mahbub        CSE

In [0]:
!pip install lxml
!pip install html5lib
!pip install BeautifulSoup4

In [0]:
df = pd.read_html("https://www.fdic.gov/bank/individual/failed/banklist.html")
df[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc

In [0]:
label = "A B C D".split()
print(label)
my_data = [1, 2, 3, 4]
arr = np.array(my_data)
print(arr)
dictionary = {'A':1, 'B':2, 'C':3, 'D':4 }
sr = pd.Series(data = my_data, index = label)   # using list 
sr1 = pd.Series(data = arr, index = label)      # using numpy array
print(sr)
print(sr1)
print(dictionary)

sr2 = pd.Series([sum, print, len])
print(sr2)                                      # print the reference

# Series indexing ...
sr3 = pd.Series(data = arr) 
print(sr3)
print(sr3[2])

sr4 = pd.Series(data = arr, index = label)
print(sr4)
print(sr4["C"])

print(sr4 + sr4)   # index wise Series sumation
print(sr3 + sr4)


['A', 'B', 'C', 'D']
[1 2 3 4]
A    1
B    2
C    3
D    4
dtype: int64
A    1
B    2
C    3
D    4
dtype: int64
{'A': 1, 'B': 2, 'C': 3, 'D': 4}
0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object
0    1
1    2
2    3
3    4
dtype: int64
3
A    1
B    2
C    3
D    4
dtype: int64
3
A    2
B    4
C    6
D    8
dtype: int64
0   NaN
1   NaN
2   NaN
3   NaN
A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64


In [0]:
# create a dataframe

from numpy.random import randint 
arr = randint(0, 100, 16).reshape(4,4)
print(arr)
rows = "A B C D".split()
cols = "E F G F".split()
df = pd.DataFrame(arr, index = rows, columns = cols)
df


[[18 27  6 20]
 [41 13  4  3]
 [78 85 24 85]
 [54 58 38 97]]


E   F   G   F
A  18  27   6  20
B  41  13   4   3
C  78  85  24  85
D  54  58  38  97

In [0]:
# array selection & indexing 

from numpy.random import randint 
arr = randint(0, 100, 12).reshape(4, 3)
print(arr)
rows = "A B C D".split()
cols = "E F G".split()
df3 = pd.DataFrame(arr, index = rows, columns = cols)
print(df3)
# print(df3["B"])      # row wise indexing is not possible, only column wise possible
print(df3["E"])        # single column value
print(df3[["E", "F"]]) # multiple column, list of list

# row access

print(df3.loc["C"])    # C row value
print(df3.iloc[2])     # also possible access row by numeric values


[[49 21 48]
 [96 35 55]
 [84 46 43]
 [68 94 52]]
    E   F   G
A  49  21  48
B  96  35  55
C  84  46  43
D  68  94  52
A    49
B    96
C    84
D    68
Name: E, dtype: int64
    E   F
A  49  21
B  96  35
C  84  46
D  68  94
E    84
F    46
G    43
Name: C, dtype: int64
E    84
F    46
G    43
Name: C, dtype: int64


In [0]:
# add & delet column

df3["new"] = df3["E"] + df3["F"]
print (df3)
print(df3.drop("new", axis = 1))   # delet a column
print(df3)                         # but the new column doesn't delet permanently
df3["new"] = df3["E"] + df3["F"]   # add agian
print(df3)
print(df3.drop("new", axis = 1, inplace = True))  # delet permanently
print(df3)

# delet row

print(df3.drop("C", axis = 0, inplace = True))
print(df3)

    E   F   G  new
A  49  21  48   70
B  96  35  55  131
C  84  46  43  130
D  68  94  52  162
    E   F   G
A  49  21  48
B  96  35  55
C  84  46  43
D  68  94  52
    E   F   G  new
A  49  21  48   70
B  96  35  55  131
C  84  46  43  130
D  68  94  52  162
    E   F   G  new
A  49  21  48   70
B  96  35  55  131
C  84  46  43  130
D  68  94  52  162
None
    E   F   G
A  49  21  48
B  96  35  55
C  84  46  43
D  68  94  52
None
    E   F   G
A  49  21  48
B  96  35  55
D  68  94  52
